import axios from "lib/axios/axios"
import { IAuthParams, IUser } from "features/shared/authentication"


export const login = (data:IAuthParams) => {
  // const {data} = axios.post('/login', data)
  // return data

  // only for test purpose
  return new Promise((resolve, reject) =>{
    setTimeout(()=>{
      resolve({
        token:'some random token generated by backend',
        role: 'candidate'
      })
    }, 500)
  })
}

// or another route which gets the current auth data
export const refresh = async():Promise<any> => { // add type
  // const { data } = await axios.get('refresh')
  // return data

  // only for test purpose
  return new Promise((resolve, reject) =>{
    setTimeout(()=>{
      resolve({
        token:'some random refresh token generated by backend', 
        role: 'candidate'
      })
    }, 500)
  })
}


export const getUser = async():Promise<IUser> => {
  const { data } = await axios.get('https://api.genderize.io?name=lucas')

  return data
}

// TODO: type param
export const findUser = (username:string, signal:any):Promise<any> => { // add type
  const searchUser =  axios.get(`https://api.nationalize.io/?name=${username}`) 

  return searchUser
}